# fly.toml app configuration file generated for drone-crop-swarm-gpu on 2026-04-08
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "drone-crop-swarm-gpu"
primary_region = "iad"

[build]
  dockerfile = "workers/Dockerfile"

[env]
  WORKER_TYPE = "gpu"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = "a100-40gb"
  gpu_kind = "a100-pcie-40gb"
  cpus = 8
  memory_mb = 32768

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
